# Site settings
title: Eddie Rangel . com
header-img: img/home-bg.jpg
email: hacker@eddierangel.com
description: "...and his Blog"
baseurl: ""
url: "http://edierangel.com"
twitter_username: eddie_31003
github_username:  erangeljr
linkedin_username: eddierangel

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]

analytics :
  provider : google
  google : 
      tracking_id : 'UA-47781516-1'